name: $(TeamProject)_$(BuildDefinitionName)_$(SourceBranchName)_$(Date:yyyyMMdd)$(Rev:.r)

trigger:
  branches:
    include:
      - master
  paths:
    exclude:
      - README.md

variables:
  vmImage: Ubuntu-16.04
  imageName: hmcts/rse-dashboard

jobs:

  - job: Main
    pool:
      vmImage: $(vmImage)
    steps:
      - task: AzureCLI@1
        displayName: 'ACR Build'
        enabled: true
        env:
          endpoint: $(endpoint)
          masterKey: $(masterKey)
          databaseId: $(databaseId)
          containerId: $(containerId)
        inputs:
          azureSubscription: $(serviceConnection)
          scriptLocation: 'inlineScript'
          inlineScript: >
            az acr build \
              --build-arg endpoint=$(endpoint) \
              --build-arg masterKey=$(masterKey) \
              --build-arg databaseId=$(databaseId) \
              --build-arg containerId=$(containerId) \
              -r $(acrName) \
              --subscription $(subscription) \
              -t $(imageName) \
              .
