name: $(TeamProject)_$(BuildDefinitionName)_$(SourceBranchName)_$(Date:yyyyMMdd)$(Rev:.r)

trigger:
  branches:
    include:
      - master
  paths:
    exclude:
      - README.md

variables:
  vmImage: Ubuntu-16.04
  imageTag: hmcts/rse-dashboard

jobs:

  - job: Main
    pool:
      vmImage: $(vmImage)
    steps:
      
      - task: Docker@1
        displayName: 'Build'
        env:
          endpoint: $(endpoint)
          masterKey: $(masterKey)
          databaseId: $(databaseId)
          containerId: $(containerId)
          acrName: $(acrName)
        inputs:
          command: "Build an image"
          azureSubscriptionEndpoint: $(serviceConnection)
          azureContainerRegistry: $(acrName).azurecr.io
          imageName: '$(acrName).azurecr.io/$(imageTag):$(Build.BuildId)'
          arguments: '--build-arg endpoint=$(endpoint) --build-arg masterKey=$(masterKey) --build-arg databaseId=$(databaseId) --build-arg containerId=$(containerId)'

      - task: Docker@2
        displayName: Login to ACR
        inputs:
          command: login
          containerRegistry: $(acrName)

      - task: Docker@1
        displayName: 'Push'
        inputs:
          command: "Push an image"
          azureSubscriptionEndpoint: '$(serviceConnection)'
          azureContainerRegistry: $(acrName).azurecr.io
          imageName: '$(acrName).azurecr.io/$(imageTag):$(Build.BuildId)'
