name: $(TeamProject)_$(BuildDefinitionName)_$(SourceBranchName)_$(Date:yyyyMMdd)$(Rev:.r)

trigger:
  branches:
    include:
      - master
  paths:
    exclude:
      - README.md

variables:
  vmImage: Ubuntu-16.04
  imageTag: hmcts/rse-dashboard

jobs:

  - job: Main
    pool:
      vmImage: $(vmImage)
    steps:
      
      - task: Docker@2
        displayName: "Build an image"
        env:
          endpoint: $(endpoint)
          masterKey: $(masterKey)
          databaseId: $(databaseId)
          containerId: $(containerId)
        inputs:
          command: build
          containerRegistry: $(serviceConnection)
          repository: $(imageTag)
          arguments: '--build-arg endpoint=$(endpoint) --build-arg masterKey=$(masterKey) --build-arg databaseId=$(databaseId) --build-arg containerId=$(containerId)'

      - task: Docker@2
        displayName: Login to ACR
        inputs:
          command: login
          containerRegistry: $(serviceConnection)

      - task: Docker@2
        displayName: "Push to ACR"
        inputs:
          command: push
          containerRegistry: $(serviceConnection)
          repository: $(imageTag)
