name: $(TeamProject)_$(BuildDefinitionName)_$(SourceBranchName)_$(Date:yyyyMMdd)$(Rev:.r)

trigger:
  branches:
    include:
      - master
  paths:
    exclude:
      - README.md

variables:
  vmImage: Ubuntu-16.04
  imageName: hmcts/rse-dashboard

jobs:

  - job: Main
    pool:
      vmImage: $(vmImage)
    steps:

      # - task: Bash@3
      #   displayName: ACR Login
      #   inputs:
      #     targetType: 'inline'
      #     script: docker login -u $registryUsername -p $registryPwd $azureContainerRegistry
      #   env:
      #     azureContainerRegistry: $(azureContainerRegistry)
      #     registryPwd: $(registryPwd)
      #     registryUsername: $(registryUsername)

      - task: Docker@1
        displayName: Login
        inputs:
          azureSubscriptionEndpoint: $(azureSubscriptionEndpoint)
          azureContainerRegistry: $(azureContainerRegistry)
          command: login

      - task: Docker@1
        displayName: Build image
        inputs:
          arguments: --build-arg endpoint=$(endpoint) --build-arg masterKey=$(masterKey) --build-arg databaseId=$(databaseId) --build-arg containerId=$(containerId)
          command: Build an image
          imageName: $(imageName)

      - task: Docker@1
        displayName: Tag image
        inputs:
          azureSubscriptionEndpoint: $(azureSubscriptionEndpoint)
          azureContainerRegistry: $(azureContainerRegistry)
          command: Tag image
          imageName: $(imageName)

      - task: Docker@1
        displayName: Push image
        inputs:
          azureSubscriptionEndpoint: $(azureSubscriptionEndpoint)
          azureContainerRegistry: $(azureContainerRegistry)
          command: Push an image
          imageName: $(imageName)

      - task: Docker@1
        displayName: ACR Logout
        inputs:
          command: logout
