name: $(TeamProject)_$(BuildDefinitionName)_$(SourceBranchName)_$(Date:yyyyMMdd)$(Rev:.r)

trigger:
  branches:
    include:
      - master
  paths:
    exclude:
      - README.md

variables:
  azureContainerRegistry: hmctssandbox.azurecr.io
  azureSubscriptionEndpoint: azurerm-sandbox
  vmImage: Ubuntu-16.04
  imageName: hmcts/rse-dashboard

jobs:

  - job: Main
    pool:
      vmImage: $(vmImage)
    steps:
      - task: Bash@3
        displayName: Build production image
        inputs:
          targetType: inline
          script: make production-image
        env:
          endpoint: $(endpoint)
          masterKey: $(masterKey)
          databaseId: $(databaseId)
          containerId: $(containerId)
      # - task: Docker@1
      #   displayName: Container registry login
      #   inputs:
      #     azureContainerRegistry: $(azureContainerRegistry)
      #     azureSubscriptionEndpoint: $(azureSubscriptionEndpoint)
      #     command: login
      # - task: Docker@1
      #   displayName: Tag image
      #   inputs:
      #     azureContainerRegistry: $(azureContainerRegistry)
      #     azureSubscriptionEndpoint: $(azureSubscriptionEndpoint)
      #     imageName: $(imageName)
      #     arguments: $(azureContainerRegistry)/$(imageName):latest
      #     command: Tag image
      # - task: Docker@1
      #   displayName: Push image
      #   inputs:
      #     azureContainerRegistry: $(azureContainerRegistry)
      #     azureSubscriptionEndpoint: $(azureSubscriptionEndpoint)
      #     command: Push an image
      #     imageName: $(azureContainerRegistry)/$(imageName):latest