name: $(TeamProject)_$(BuildDefinitionName)_$(SourceBranchName)_$(Date:yyyyMMdd)$(Rev:.r)

trigger:
  branches:
    include:
      - master
  paths:
    exclude:
      - README.md

schedules:
  - cron: 58 9-17/2 * * 1-5
    displayName: Workhours hourly build
    branches:
      include:
        - master
    always: true

variables:
  vmImage: Ubuntu-16.04
  imageName: hmcts/rse-dashboard

jobs:

  - job: Main
    pool:
      vmImage: $(vmImage)
    steps:

      - task: Docker@1
        displayName: ACR Login
        inputs:
          azureSubscriptionEndpoint: $(azureSubscriptionEndpoint)
          azureContainerRegistry: $(azureContainerRegistry)
          command: login

      - task: Docker@1
        displayName: Build image
        inputs:
          arguments: --build-arg endpoint=$(endpoint) --build-arg masterKey=$(masterKey) --build-arg databaseId=$(databaseId) --build-arg containerId=$(containerId) --build-arg githubtoken=$(githubtoken)
          command: Build an image
          imageName: $(imageName)

      - task: Docker@1
        displayName: Tag image
        inputs:
          azureSubscriptionEndpoint: $(azureSubscriptionEndpoint)
          azureContainerRegistry: $(azureContainerRegistry)
          command: Tag image
          imageName: $(imageName)

      - task: Docker@1
        displayName: Push image
        inputs:
          azureSubscriptionEndpoint: $(azureSubscriptionEndpoint)
          azureContainerRegistry: $(azureContainerRegistry)
          command: Push an image
          imageName: $(imageName)

      - task: Docker@1
        displayName: ACR Logout
        inputs:
          command: logout
