name: $(TeamProject)_$(BuildDefinitionName)_$(SourceBranchName)_$(Date:yyyyMMdd)$(Rev:.r)

trigger:
  branches:
    include:
      - master
  paths:
    exclude:
      - README.md

variables:
  azureContainerRegistry: hmctssandbox.azurecr.io
  azureSubscriptionEndpoint: azurerm-sandbox
  serviceConnection: azurerm-sandbox
  acrName: hmctssandbox
  acrResourceGroup: cnp-acr-rg
  vmImage: Ubuntu-16.04
  imageName: hmcts/rse-dashboard

jobs:

  - job: Main
    pool:
      vmImage: $(vmImage)
    steps:
      - task: Bash@3
        displayName: Build production image
        inputs:
          targetType: inline
          script: make production-image
        env:
          endpoint: $(endpoint)
          masterKey: $(masterKey)
          databaseId: $(databaseId)
          containerId: $(containerId)
      # - task: AzureCLI@1
      #   displayName: 'ACR Build'
      #   enabled: true
      #   inputs:
      #     azureSubscription: $(serviceConnection)
      #     scriptLocation: 'inlineScript'
      #     inlineScript: az acr build -r $(acrName) -t imageName -g $(acrResourceGroup) .